from django.urls import path

from university import views

urlpatterns=[
    path('',views.main,name="main"),
    path('logn', views.logn, name="logn"),
    path('allocatestaff/<int:id>',views.allocatestaff,name="allocatestaff"),
    path('allocatestaffbtn',views.allocatestaffbtn,name="allocatestaffbtn"),
    path('clgregist',views.clgregist,name="clgregist"),
    path('studentregist',views.studentregist,name="studentregist"),
    path('staffregist',views.staffregist,name="staffregist"),
    path('addcomplaint',views.addcomplaint,name="addcomplaint"),
    path('examschedule',views.examschedule,name="examschedule"),
    path('adddepartment',views.adddepartment,name="adddepartment"),
    path('addcourse',views.addcourse,name="addcourse"),
    path('request_ans',views.request_ans,name="request_ans"),
    path('addresult',views.addresult,name="addresult"),
    path('req_revaluation',views.req_revaluation,name="req_revaluation"),
    path('addsubject',views.addsubject,name="addsubject"),
    path('uploadanswer',views.uploadanswer,name="uploadanswer"),
    path('view_allocatestaff',views.view_allocatestaff,name="view_allocatestaff"),
    path('clg_details',views.clg_details,name="clg_details"),
    path('view_staff',views.view_staff,name="view_staff"),
    path('view_student',views.view_student,name="view_student"),
    path('view_exam',views.view_exam,name="view_exam"),
    path('view_department',views.view_department,name="view_department"),
    path('view_course',views.view_course,name="view_course"),
    path('view_subject',views.view_subject,name="view_subject"),
    path('view_answersheet',views.view_answersheet,name="view_answersheet"),
    path('view_result',views.view_result,name="view_result"),
    path('view_revaluation',views.view_revaluation,name="view_revaluation"),
    path('view_complaint',views.view_complaint,name="view_complaint"),
    path('view_stdcomplaint',views.view_stdcomplaint,name="view_stdcomplaint"),
    path('delete/<int:id>', views.delete, name="delete"),
    path('deletestudent/<int:id>', views.deletestudent, name="deletestudent"),
    path('adminallocatestaff', views.adminallocatestaff, name="adminallocatestaff"),
    path('allocstf/<int:id>', views.allocstf, name="allocstf"),
    path('view_ansrequest', views.view_ansrequest, name="view_ansrequest"),
    path('admin_staffaloc', views.admin_staffaloc, name="admin_staffaloc"),
    path('request_ansadd', views.request_ansadd, name="request_ansadd"),
    path('stfwork', views.stfwork, name="stfwork"),

    path('clgreg',views.clgreg,name="clgreg"),
    path('stfreg',views.stfreg,name="stfreg"),
    path('stdreg',views.stdreg,name="stdreg"),
    path('deptbtn', views.deptbtn, name="deptbtn"),
    path('compreply', views.compreply, name="compreply"),
    path('exambtn', views.exambtn, name="exambtn"),
    path('reply/<int:id>', views.reply, name="reply"),
    path('approve/<int:id>', views.approve, name="approve"),
    path('reject/<int:id>', views.reject, name="reject"),
    path('coursebtn', views.coursebtn, name="coursebtn"),
    path('subjbtn', views.subjbtn, name="subjbtn"),
    path('complaintbtn', views.complaintbtn, name="complaintbtn"),
    path('search', views.search, name="search"),
    path('searchstaff', views.searchstaff, name="searchstaff"),
    path('searchstud', views.searchstud, name="searchstud"),
    path('updanswer', views.updanswer, name="updanswer"),
    path('searchcrs', views.searchcrs, name="searchcrs"),
    path('view_adminexam', views.view_adminexam, name="view_adminexam"),
    path('staffaloc', views.staffaloc, name="staffaloc"),
    path('reqansbtn', views.reqansbtn, name="reqansbtn"),
    path('user_pay_proceed/<int:id>', views.user_pay_proceed, name="user_pay_proceed"),
    path('clgresult', views.clgresult, name="clgresult"),
    path('stfresult', views.stfresult, name="stfresult"),
    path('revalallocatestaff', views.revalallocatestaff, name="revalallocatestaff"),
    path('revalallocstf/<int:id>', views.revalallocstf, name="revalallocstf"),
    path('admin_revalstaffaloc', views.admin_revalstaffaloc, name="admin_revalstaffaloc"),
    path('stfrevwork', views.stfrevwork, name="stfrevwork"),
    path('revallocatestaffbtn', views.revallocatestaffbtn, name="revallocatestaffbtn"),
    path('revallocatestaff/<int:id>', views.revallocatestaff, name="revallocatestaff"),
    path('view_examstaff', views.view_examstaff, name="view_examstaff"),
    path('view_examstudent', views.view_examstudent, name="view_examstudent"),
    path('clgprofile', views.clgprofile, name="clgprofile"),
    path('stfprofile', views.stfprofile, name="stfprofile"),
    path('stdntprofile', views.stdntprofile, name="stdntprofile"),
    path('searchresult', views.searchresult, name="searchresult"),
    path('paschange', views.paschange, name="paschange"),


    path('admin',views.admin,name="admin"),
    path('stafpage',views.stafpage,name="stafpage"),
    path('myclg',views.myclg,name="myclg"),
    path('stud',views.stud,name="stud"),
    path('user_pay_proceed1',views.user_pay_proceed1,name="user_pay_proceed1"),
    # path('on_payment_success',views.on_payment_success,name="on_payment_success"),
    path('logout',views.logout, name="logout"),

]