# Generated by Django 3.1.5 on 2023-04-27 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revaluation',
            name='result_id',
        ),
        migrations.AddField(
            model_name='revaluation',
            name='answersheet_id',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='university.answersheet'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='result',
        ),
    ]
