# Generated by Django 3.2.18 on 2023-05-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='hashvalue',
            field=models.CharField(default=22, max_length=300),
            preserve_default=False,
        ),
    ]
