# Generated by Django 3.2.18 on 2023-05-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_answersheet_hashvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(default=23, max_length=100),
            preserve_default=False,
        ),
    ]
