# Generated by Django 3.1.5 on 2023-04-30 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20230427_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='stafrevalallocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('revaluation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.revaluation')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.staff')),
            ],
        ),
    ]
